name: quizapp_flutter
description: A new Flutter application.

publish_to: 'none'
version: 1.7.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  nb_utils: ^5.0.8
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  google_fonts: ^4.0.4
  url_launcher: ^6.1.10
  package_info_plus: ^3.1.2
  flutter_vector_icons: ^2.0.0
  intl: ^0.18.1
  flutter_advanced_drawer: ^1.3.5

  firebase_core: ^2.11.0
  firebase_storage: ^11.1.2
  cloud_firestore: ^4.6.0
  firebase_analytics: ^10.3.0
  google_sign_in: ^6.1.0
  firebase_auth: ^4.5.0
  google_mobile_ads: ^3.0.0

  otp_text_field: ^1.1.3
  image_picker: ^0.8.7+4
  flutter_countdown_timer: ^4.1.0
  cached_network_image: ^3.2.3
  dots_indicator: ^3.0.0
  onesignal_flutter: ^3.5.1
  device_info_plus: ^8.2.2
  flutter_fortune_wheel: ^1.2.0
  motion_toast: ^2.6.7
  flutter_staggered_animations: ^1.1.1
  share_plus: ^6.3.4
  wheel_spin: ^1.0.2
  country_code_picker: ^3.0.0
  shake_animation_widget: ^3.0.4

  flutter_localizations:
    sdk: flutter
  modal_bottom_sheet: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  mobx_codegen: ^2.2.0

  #flutter packages pub run build_runner build --delete-conflicting-outputs



dependency_overrides:
  intl: ^0.18.1
#  firebase_core: ^1.21.1
#  firebase_storage: ^10.3.7
#  cloud_firestore: ^3.4.6
#  firebase_analytics: ^9.3.3
#  google_sign_in: ^5.4.1
#  firebase_auth: ^3.7.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/flag/
    - lang/
